const restaurantsList = [
  {
    id: 1,
    name: "Spice Garden",
    cuisine: ["North Indian", "Chinese"],
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceForTwo: 450,
    location: "Pune",
    isVeg: false,
    image: "https://example.com/spice-garden.jpg",
  },
  {
    id: 2,
    name: "Green Leaf",
    cuisine: ["South Indian", "Pure Veg"],
    rating: 4.2,
    deliveryTime: "20-25 min",
    priceForTwo: 300,
    location: "Pune",
    isVeg: true,
    image: "https://example.com/green-leaf.jpg",
  },
  {
    id: 3,
    name: "Pizza Hub",
    cuisine: ["Pizza", "Italian"],
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceForTwo: 550,
    location: "Mumbai",
    isVeg: false,
    image: "https://example.com/pizza-hub.jpg",
  },
  {
    id: 4,
    name: "Burger Singh",
    cuisine: ["Burgers", "Fast Food"],
    rating: 4.1,
    deliveryTime: "20-25 min",
    priceForTwo: 350,
    location: "Nagpur",
    isVeg: false,
    image: "https://example.com/burger-singh.jpg",
  },
  {
    id: 5,
    name: "Maharaja Thali",
    cuisine: ["North Indian", "Rajasthani"],
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceForTwo: 500,
    location: "Pune",
    isVeg: true,
    image: "https://example.com/maharaja-thali.jpg",
  },
  {
    id: 6,
    name: "Dragon Bowl",
    cuisine: ["Chinese", "Asian"],
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceForTwo: 600,
    location: "Mumbai",
    isVeg: false,
    image: "https://example.com/dragon-bowl.jpg",
  },
  {
    id: 7,
    name: "Dosa Corner",
    cuisine: ["South Indian"],
    rating: 4.4,
    deliveryTime: "15-20 min",
    priceForTwo: 250,
    location: "Nagpur",
    isVeg: true,
    image: "https://example.com/dosa-corner.jpg",
  },
  {
    id: 8,
    name: "Tandoori Nights",
    cuisine: ["North Indian", "Mughlai"],
    rating: 4.8,
    deliveryTime: "30-35 min",
    priceForTwo: 700,
    location: "Pune",
    isVeg: false,
    image: "https://example.com/tandoori-nights.jpg",
  },
  {
    id: 9,
    name: "Cafe Coffee House",
    cuisine: ["Cafe", "Desserts", "Beverages"],
    rating: 4.0,
    deliveryTime: "15-20 min",
    priceForTwo: 400,
    location: "Mumbai",
    isVeg: true,
    image: "https://example.com/cafe-coffee-house.jpg",
  },
  {
    id: 10,
    name: "Biryani Express",
    cuisine: ["Biryani", "Hyderabadi"],
    rating: 4.6,
    deliveryTime: "25-30 min",
    priceForTwo: 500,
    location: "Pune",
    isVeg: false,
    image: "https://example.com/biryani-express.jpg",
  },
];


export default restaurantsList